export interface Product {
  product_id: string;
  sku: string | null;
  upc: string | null;
  ean: string | null;
  name: string;
  slug: string;
  description: string | null;
  short_description: string | null;
  category_id: string | null;
  brand_id: string | null;
  tags: string[] | null;
  base_price: number;
  discount_price: number | null;
  cost_price: number | null;
  currency: string;
  tax_category: string | null;
  tax_rate: number | null;
  is_taxable: boolean;
  stock_quantity: number;
  min_stock_threshold: number;
  is_in_stock: boolean;
  backorder_allowed: boolean;
  weight: number | null;
  weight_unit: string;
  length: number | null;
  width: number | null;
  height: number | null;
  dimension_unit: string;
  has_variants: boolean;
  parent_product_id: string | null;
  variant_attributes: Record<string, any> | null;
  is_digital: boolean;
  digital_file_path: string | null;
  download_limit: number | null;
  main_image_url: string | null;
  additional_images: string[] | null;
  video_url: string | null;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  search_terms: string[] | null;
  status: 'draft' | 'published' | 'archived' | 'discontinued';
  visibility: 'visible' | 'hidden' | 'search_only' | 'catalog_only';
  featured: boolean;
  is_shippable: boolean;
  shipping_class: string | null;
  free_shipping: boolean;
  shipping_weight: number | null;
  supplier_id: string | null;
  supplier_sku: string | null;
  lead_time: number | null;
  min_order_quantity: number;
  warranty_info: string | null;
  return_policy_id: string | null;
  average_rating: number | null;
  rating_count: number;
  review_count: number;
  related_products: string[] | null;
  upsell_products: string[] | null;
  cross_sell_products: string[] | null;
  created_at: string;
  updated_at: string;
  published_at: string | null;
  created_by: string | null;
  updated_by: string | null;
  custom_attributes: Record<string, any> | null;
}

export interface ProductFormData {
  name: string;
  sku: string;
  upc: string;
  ean: string;
  description: string;
  short_description: string;
  base_price: number;
  stock_quantity: number;
  status: 'draft' | 'published' | 'archived' | 'discontinued';
  visibility: 'visible' | 'hidden' | 'search_only' | 'catalog_only';
  is_digital: boolean;
  main_image_url: string;
}