/*
  # Insert Sample Products

  1. Changes
    - Inserts 20 sample products with realistic data
    - Includes various product types and categories
    - Sets realistic prices and stock quantities
*/

INSERT INTO products (
  name,
  sku,
  description,
  short_description,
  base_price,
  stock_quantity,
  status,
  visibility,
  slug,
  is_in_stock,
  currency,
  weight_unit,
  dimension_unit
) VALUES
  (
    'Professional Gaming Mouse',
    'GM-001',
    'High-precision gaming mouse with 16000 DPI optical sensor and RGB lighting. Features 8 programmable buttons and ergonomic design.',
    'High-performance gaming mouse with RGB',
    79.99,
    150,
    'published',
    'visible',
    'professional-gaming-mouse',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Mechanical Keyboard - Blue Switch',
    'KB-002',
    'Premium mechanical keyboard with blue switches, full RGB backlighting, and aluminum frame. Perfect for gaming and typing.',
    'RGB mechanical keyboard with blue switches',
    129.99,
    75,
    'published',
    'visible',
    'mechanical-keyboard-blue-switch',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Ultra-Wide Gaming Monitor 34"',
    'MON-003',
    '34-inch curved ultra-wide monitor with 3440x1440 resolution, 144Hz refresh rate, and 1ms response time.',
    '34" ultra-wide gaming monitor',
    699.99,
    25,
    'published',
    'visible',
    'ultra-wide-gaming-monitor-34',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Wireless Gaming Headset',
    'HS-004',
    'Premium wireless gaming headset with 7.1 surround sound, noise-canceling microphone, and 30-hour battery life.',
    'Wireless gaming headset with surround sound',
    159.99,
    100,
    'published',
    'visible',
    'wireless-gaming-headset',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'RGB Gaming Mouse Pad XL',
    'MP-005',
    'Extra-large RGB gaming mouse pad with 10 lighting modes. Non-slip base and smooth surface.',
    'XL RGB gaming mouse pad',
    29.99,
    200,
    'published',
    'visible',
    'rgb-gaming-mouse-pad-xl',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming PC Case - Tempered Glass',
    'CASE-006',
    'Mid-tower gaming case with tempered glass panel, excellent airflow, and RGB fan support.',
    'Premium gaming PC case',
    89.99,
    45,
    'published',
    'visible',
    'gaming-pc-case-tempered-glass',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Chair - Pro Series',
    'CHR-007',
    'Ergonomic gaming chair with adjustable armrests, lumbar support, and reclining function.',
    'Professional gaming chair',
    249.99,
    30,
    'published',
    'visible',
    'gaming-chair-pro-series',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'RTX 4070 Graphics Card',
    'GPU-008',
    'High-performance graphics card with ray tracing and DLSS support. 12GB GDDR6X memory.',
    'RTX 4070 gaming graphics card',
    599.99,
    15,
    'published',
    'visible',
    'rtx-4070-graphics-card',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Desk - LED Edition',
    'DSK-009',
    'Gaming desk with built-in LED lighting, cable management, and cup holder. Carbon fiber texture.',
    'LED gaming desk',
    199.99,
    20,
    'published',
    'visible',
    'gaming-desk-led-edition',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Stream Deck Mini',
    'STR-010',
    'Compact stream controller with 6 customizable LCD keys. Perfect for content creators.',
    'Mini stream controller',
    79.99,
    60,
    'published',
    'visible',
    'stream-deck-mini',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'USB Microphone - Pro',
    'MIC-011',
    'Professional USB condenser microphone with multiple pickup patterns and zero-latency monitoring.',
    'Professional USB microphone',
    129.99,
    40,
    'published',
    'visible',
    'usb-microphone-pro',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Webcam 4K Pro',
    'WC-012',
    '4K webcam with autofocus, low-light correction, and built-in privacy shutter.',
    '4K professional webcam',
    149.99,
    55,
    'published',
    'visible',
    'webcam-4k-pro',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Router - Wi-Fi 6',
    'RTR-013',
    'High-performance gaming router with Wi-Fi 6, low latency, and gaming traffic prioritization.',
    'Wi-Fi 6 gaming router',
    299.99,
    25,
    'published',
    'visible',
    'gaming-router-wifi-6',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'RGB Case Fans 3-Pack',
    'FAN-014',
    'Pack of 3 RGB case fans with PWM control and synchronized lighting effects.',
    'RGB case fans pack',
    49.99,
    100,
    'published',
    'visible',
    'rgb-case-fans-3-pack',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Speakers 2.1',
    'SPK-015',
    '2.1 gaming speaker system with RGB lighting, bluetooth connectivity, and powerful bass.',
    'Gaming speakers with subwoofer',
    179.99,
    35,
    'published',
    'visible',
    'gaming-speakers-2-1',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Capture Card HD60',
    'CAP-016',
    'Game capture card with 1080p60 recording, instant streaming capability, and low latency.',
    'HD game capture card',
    159.99,
    45,
    'published',
    'visible',
    'capture-card-hd60',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Wrist Rest',
    'WR-017',
    'Memory foam wrist rest with cooling gel and anti-slip base. Perfect for long gaming sessions.',
    'Ergonomic gaming wrist rest',
    24.99,
    150,
    'published',
    'visible',
    'gaming-wrist-rest',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Cable Management Kit',
    'CBL-018',
    'Complete cable management kit with sleeves, clips, and ties. Keep your setup clean and organized.',
    'Professional cable management kit',
    19.99,
    200,
    'published',
    'visible',
    'cable-management-kit',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Gaming Laptop Stand',
    'STD-019',
    'Adjustable laptop stand with built-in cooling fans and cable management. RGB lighting.',
    'RGB gaming laptop stand',
    49.99,
    75,
    'published',
    'visible',
    'gaming-laptop-stand',
    true,
    'USD',
    'g',
    'cm'
  ),
  (
    'Anti-Blue Light Glasses',
    'GLS-020',
    'Gaming glasses with anti-blue light technology and comfortable frame. Reduces eye strain.',
    'Gaming anti-blue light glasses',
    39.99,
    120,
    'published',
    'visible',
    'anti-blue-light-glasses',
    true,
    'USD',
    'g',
    'cm'
  );